### ISSUE TITLE
Optional: Alternative CSS?  For Criteria: Polished UI

### ISSUE THREAD

**Issue by JenevaRay** [JenevaRay/Codeathon#19]
CSS-in-JS?  (libraries: styled-components, Emotion)
Component Library (libraries: Semantic UI, Chakra UI, Ant Design)
Plain Old CSS?
SCSS?

**Comment by JenevaRay** [comment]
We opted for Tailwind

**Comment by christianbmartinez** [comment]
Yep, tailwind has everything we need and more!
